// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ABFAboutUs.tsx": () => import("../components/mockups/ABFAboutUs.tsx"),
  "./components/mockups/ABFHomepage.tsx": () => import("../components/mockups/ABFHomepage.tsx"),
  "./components/mockups/ABFProjects.tsx": () => import("../components/mockups/ABFProjects.tsx"),
  "./components/mockups/ABFLatest.tsx": () => import("../components/mockups/ABFLatest.tsx"),
  "./components/mockups/ABFTeam.tsx": () => import("../components/mockups/ABFTeam.tsx"),
  "./components/mockups/ABFGetInvolved.tsx": () => import("../components/mockups/ABFGetInvolved.tsx")
};
