// This file is auto-generated by mockupPreviewPlugin.ts.
// It has been manually updated to register the ABF Homepage component.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ABFHomepage.tsx": () => import("../components/mockups/ABFHomepage"),
};
